
#- name: Read the ACL before changes.
#  ios_command:
#    provider: "{{ provider }}"
#    commands:
#      - "show access-list {{ acl['name'] }}"
#  register: before_acl

#- name: Print the current ACL.
#  debug: var=before_acl.stdout_lines

- name: Configure the ACLs on the devices.
  ios_config:
    provider: "{{ provider }}"
    authorize: yes
    before: "no ip access-list extended {{ acl['name'] }}"
    parents: "ip access-list extended {{ acl['name'] }}"
    lines: "{{ acl['lines'] }}"
    match: exact
    replace: block
    diff_against: running
#  register: config_run

#- debug: var=config_run

#- name: Read the ACL after changes.
#  ios_command:
#    provider: "{{ provider }}"
#    commands:
#      - "show access-list {{ acl['name'] }}"
#  register: after_acl

#- name: Print the updated ACL.
#  debug: var=after_acl.stdout_lines
